import { useEffect, useState } from 'react';
import { useTranslation } from 'react-i18next';
import { formatDisplayDate, formatDisplayNumber } from './localization.js';

const statusClass = (status) => `status-${String(status || '').toLowerCase().replaceAll(' ', '-')}`;
export const dashboardGreeting = (language, date = new Date()) => language === 'ar' ? (date.getHours() < 12 ? 'صباح الخير' : 'مساء الخير') : (date.getHours() < 12 ? 'Good morning' : date.getHours() < 17 ? 'Good afternoon' : 'Good evening');
const greetingDelay = (date) => { const next = new Date(date); next.setHours(date.getHours() < 12 ? 12 : date.getHours() < 17 ? 17 : 24, 0, 0, 0); return next - date; };

function DashboardPage({ onProducts, onDetails, user }) {
  const { t, i18n } = useTranslation();
  const [data, setData] = useState(null); const [error, setError] = useState(''); const [search, setSearch] = useState(''); const [now, setNow] = useState(() => new Date());
  useEffect(() => { let timer; const update = () => { const current = new Date(); setNow(current); timer = setTimeout(update, greetingDelay(current) + 25); }; timer = setTimeout(update, greetingDelay(now) + 25); return () => clearTimeout(timer); }, []);
  const normalizedSearch = search.trim();
  useEffect(() => { const controller = new AbortController(); let current = true; const query = normalizedSearch ? `?${new URLSearchParams({ search: normalizedSearch })}` : ''; fetch(`/api/dashboard${query}`, { credentials: 'include', signal: controller.signal }).then(async (response) => { const body = await response.json(); if (!response.ok) throw new Error(t('dashboard.load')); if (!body.statistics || !Array.isArray(body.recentlyAdded) || !Array.isArray(body.nearestExpiration)) throw new Error(t('dashboard.invalid')); return body; }).then((body) => { if (current) { setData(body); setError(''); } }).catch((cause) => { if (current && cause.name !== 'AbortError') setError(cause.message === t('dashboard.invalid') ? t('dashboard.invalid') : t('dashboard.load')); }); return () => { current = false; controller.abort(); }; }, [t, normalizedSearch]);
  if (error) return <main className="products-page"><p className="error" role="alert">{error}</p></main>;
  if (!data) return <main className="products-page"><p role="status">{t('common.loading')}</p></main>;

  const { total = 0, active = 0, expiringSoon = 0, expired = 0 } = data.statistics;
  const cards = [[t('dashboard.active'), active, 'Active', '✓'], [t('dashboard.expiring'), expiringSoon, 'Expiring Soon', '◷'], [t('dashboard.expired'), expired, 'Expired', '!'], [t('dashboard.total'), total, '', '▣']];
  const totalForChart = total || 1; const activePercent = Math.round((active / totalForChart) * 100); const expiringPercent = Math.round((expiringSoon / totalForChart) * 100); const expiredPercent = Math.round((expired / totalForChart) * 100);
  const chartStyle = { '--active': `${activePercent * 3.6}deg`, '--expiring': `${(activePercent + expiringPercent) * 3.6}deg` };
  const allProducts = [...new Map([...data.recentlyAdded, ...data.nearestExpiration].map((product) => [product.id, product])).values()];
  const searchResults = normalizedSearch ? (data.searchResults || allProducts.filter((product) => `${product.name} ${product.storeName || ''} ${product.serialNumber || ''}`.toLowerCase().includes(normalizedSearch.toLowerCase()))) : [];
  const category = (value) => t(`categories.${value}`, { defaultValue: value }); const status = (value) => t(`status.${value}`, { defaultValue: value });
  const displayDate = (value) => value ? formatDisplayDate(value, i18n.language) : '—';
  const productTable = (products, label) => products.length ? <div className="recent-table-wrap"><table aria-label={label}><thead><tr><th>{t('common.product')}</th><th>{t('common.purchaseDate')}</th><th>{t('common.expiresOn')}</th><th>{t('common.status')}</th></tr></thead><tbody>{products.map((product) => <tr key={product.id}><td><button type="button" className="text-button" onClick={() => onDetails?.(product.id)}><strong dir="auto">{product.name}</strong></button><small dir="auto">{product.storeName || category(product.category)}</small></td><td><bdi>{displayDate(product.purchaseDate)}</bdi></td><td><bdi>{displayDate(product.expirationDate)}</bdi></td><td><span className={`status-badge ${statusClass(product.warrantyStatus)}`}>{status(product.warrantyStatus)}</span></td></tr>)}</tbody></table></div> : <p className="empty-state" role="status">{t('dashboard.noSearchResults')}</p>;

  return <main className="products-page dashboard dashboard-reference">
    <h2 className="visually-hidden">{t('dashboard.title')}</h2><header className="dashboard-topbar"><div><h1>{user?.fullName ? t('dashboard.greetingWithName', { greeting: dashboardGreeting(i18n.language, now), name: user.fullName }) : dashboardGreeting(i18n.language, now)} <span aria-hidden="true">👋</span></h1><p>{t('dashboard.intro')}</p></div><div className="dashboard-actions"><label className="dashboard-search"><span aria-hidden="true">⌕</span><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder={t('dashboard.search')} aria-label={t('dashboard.search')} /></label><button type="button" className="dashboard-add" onClick={() => onProducts('', { openAdd: true })}><span aria-hidden="true">＋</span>{t('dashboard.addProduct')}</button></div></header>
    {normalizedSearch ? <section className="dashboard-panel recent-panel"><div className="dashboard-panel-heading"><h2>{t('dashboard.searchResults')}</h2></div>{productTable(searchResults, t('dashboard.searchResults'))}</section> : <>
      <section className="dashboard-cards dashboard-summary-cards" aria-label={t('dashboard.title')}>{cards.map(([label, value, filter, icon]) => <button className={`dashboard-card ${statusClass(filter)}`} key={label} onClick={() => onProducts(filter)}><span className="card-icon" aria-hidden="true">{icon}</span><strong>{label}</strong><span className="dashboard-count">{formatDisplayNumber(value, i18n.language)}</span><small>{t('dashboard.all')}</small></button>)}</section>
      <section className="dashboard-main-grid"><section className="dashboard-panel expiring-panel"><div className="dashboard-panel-heading"><h2>{t('dashboard.upcoming')}</h2><button type="button" className="text-button" onClick={() => onProducts('Expiring Soon')}>{t('dashboard.view')}</button></div>{data.nearestExpiration.length ? <ul className="expiry-list">{data.nearestExpiration.slice(0, 4).map((product) => { const days = Math.max(0, Number(product.remainingWarrantyDays) || 0); return <li key={product.id}><div className="product-thumb" aria-hidden="true">▣</div><div><button type="button" className="text-button" onClick={() => onDetails?.(product.id)}><strong dir="auto">{product.name}</strong></button><small dir="auto">{product.storeName || category(product.category)}</small><span className="expiry-progress"><i style={{ width: `${Math.max(12, Math.min(100, 100 - days))}%` }} /></span></div><div className="expiry-meta"><strong>{t('products.remainingDays', { count: formatDisplayNumber(days, i18n.language) })}</strong><small><bdi>{displayDate(product.expirationDate)}</bdi></small></div></li>; })}</ul> : <p className="empty-state">{t('dashboard.noNearest')}</p>}</section><section className="dashboard-panel overview-panel"><div className="dashboard-panel-heading"><h2>{t('dashboard.overview')}</h2><span className="year-pill">{t('dashboard.thisYear')}</span></div><div className="chart-content"><div className="donut-chart" style={chartStyle}><div><strong>{formatDisplayNumber(total, i18n.language)}</strong><small>{t('dashboard.all')}</small></div></div><ul className="chart-legend"><li><i className="legend-active" />{t('status.Active')}<b>{formatDisplayNumber(activePercent, i18n.language)}%</b></li><li><i className="legend-expiring" />{t('status.Expiring Soon')}<b>{formatDisplayNumber(expiringPercent, i18n.language)}%</b></li><li><i className="legend-expired" />{t('status.Expired')}<b>{formatDisplayNumber(expiredPercent, i18n.language)}%</b></li></ul></div></section></section>
      <section className="dashboard-panel recent-panel"><div className="dashboard-panel-heading"><h2>{t('dashboard.recent')}</h2><button type="button" className="text-button" onClick={() => onProducts()}>{t('dashboard.view')}</button></div>{data.recentlyAdded.length ? productTable(data.recentlyAdded.slice(0, 5), t('dashboard.recent')) : <p className="empty-state">{t('dashboard.noRecent')}</p>}</section>
    </>}
  </main>;
}
export default DashboardPage;
