import { useEffect, useState } from 'react';

function ProfilePage({ onUserUpdated, onSessionExpired }) {
  const [profile, setProfile] = useState(null); const [name, setName] = useState(''); const [passwords, setPasswords] = useState({ currentPassword: '', newPassword: '', confirmPassword: '' }); const [message, setMessage] = useState(''); const [error, setError] = useState(''); const [saving, setSaving] = useState(false);
  useEffect(() => { fetch('/api/profile', { credentials: 'include' }).then(async r => { const contentType = r.headers.get('content-type') || ''; if (!contentType.includes('application/json')) throw new Error('Profile service returned an invalid response.'); const result = await r.json(); if (r.status === 401) { onSessionExpired(); return; } if (!r.ok) throw new Error(result.error || 'Unable to load profile.'); setProfile(result.data); setName(result.data.fullName); }).catch(e => setError(e.message || 'Unable to load profile.')); }, [onSessionExpired]);
  const saveName = async (event) => { event.preventDefault(); setSaving(true); setError(''); try { const r = await fetch('/api/profile', { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ fullName: name }) }); const d = await r.json(); if (!r.ok) throw new Error(d.errors?.fullName || d.error); setMessage(d.message); onUserUpdated(d.user); } catch (e) { setError(e.message); } finally { setSaving(false); } };
  const changePassword = async (event) => { event.preventDefault(); setSaving(true); setError(''); try { const r = await fetch('/api/profile/password', { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(passwords) }); const d = await r.json(); if (!r.ok) throw new Error(Object.values(d.errors || {})[0] || d.error); setMessage(d.message); setPasswords({ currentPassword: '', newPassword: '', confirmPassword: '' }); } catch (e) { setError(e.message); } finally { setSaving(false); } };
  if (error && !profile) return <main className="products-page"><p className="error" role="alert">{error}</p></main>;
  if (!profile) return <main className="products-page"><p role="status">Loading profile...</p></main>;
  return <main className="products-page profile-page"><h1>Profile</h1>{message && <p className="success" role="status">{message}</p>}{error && <p className="error" role="alert">{error}</p>}<section className="product-form-card"><h2>Account details</h2><p><strong>Email:</strong> {profile.email}</p><p><strong>Account created:</strong> {new Date(profile.createdAt).toLocaleDateString()}</p><form onSubmit={saveName}><label htmlFor="profile-name">Full name</label><input id="profile-name" value={name} onChange={e => setName(e.target.value)} /><button disabled={saving}>{saving ? 'Saving...' : 'Save name'}</button></form></section><section className="product-form-card"><h2>Change password</h2><form onSubmit={changePassword}>{[['currentPassword','Current password'],['newPassword','New password'],['confirmPassword','Confirm new password']].map(([key,label]) => <label key={key}>{label}<input type="password" value={passwords[key]} onChange={e => setPasswords(p => ({ ...p, [key]: e.target.value }))} /></label>)}<button disabled={saving}>{saving ? 'Saving...' : 'Change password'}</button></form></section></main>;
}
export default ProfilePage;
