import { useEffect, useState } from 'react';
import { useTranslation } from 'react-i18next';
import { formatDisplayDate, translateApiError } from './localization.js';

function ProfilePage({ onUserUpdated, onSessionExpired }) {
  const { t, i18n } = useTranslation();
  const [profile, setProfile] = useState(null); const [name, setName] = useState(''); const [passwords, setPasswords] = useState({ currentPassword: '', newPassword: '', confirmPassword: '' }); const [message, setMessage] = useState(''); const [error, setError] = useState(''); const [errorKey, setErrorKey] = useState(''); const [saving, setSaving] = useState(false);
  useEffect(() => { fetch('/api/profile', { credentials: 'include' }).then(async (response) => { const type = response.headers.get('content-type') || ''; if (!type.includes('application/json')) throw new Error('profile.invalid'); const data = await response.json(); if (response.status === 401) return onSessionExpired(); if (!response.ok) throw new Error('profile.load'); setProfile(data.data); setName(data.data.fullName); }).catch((cause) => setErrorKey(cause.message === 'profile.invalid' ? 'profile.invalid' : 'profile.load')); }, [onSessionExpired]);
  async function saveName(event) { event.preventDefault(); setMessage(''); setError(''); const normalizedName = name.trim(); if (!normalizedName) { setError(t('profile.nameRequired')); return; } if (normalizedName.length < 2) { setError(t('authValidation.fullNameMin')); return; } setSaving(true); try { const response = await fetch('/api/profile', { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ fullName: normalizedName }) }); const data = await response.json(); if (!response.ok) throw new Error(response.status === 400 ? t('profile.nameRequired') : translateApiError(data.error, t, response.status)); setName(normalizedName); setProfile((current) => ({ ...current, fullName: normalizedName })); setMessage(t('profile.updated')); onUserUpdated(data.user); } catch (cause) { setError(cause.message || t('profile.load')); } finally { setSaving(false); } }
  async function changePassword(event) { event.preventDefault(); setError(''); setErrorKey(''); setMessage(''); if (!passwords.currentPassword || !passwords.newPassword || !passwords.confirmPassword) return setErrorKey('profile.completePasswords'); if (passwords.newPassword.length < 8) return setErrorKey('profile.passwordMin'); if (passwords.newPassword !== passwords.confirmPassword) return setErrorKey('profile.passwordMismatch'); setSaving(true); try { const response = await fetch('/api/profile/password', { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(passwords) }); const contentType = response.headers?.get?.('content-type') || ''; if (!contentType.includes('application/json')) throw new Error('profile.passwordChangeError'); const data = await response.json(); if (!response.ok) { if (data.errors?.currentPassword) throw new Error('profile.currentPasswordIncorrect'); if (data.errors?.newPassword) throw new Error('profile.passwordMin'); if (data.errors?.confirmPassword) throw new Error('profile.passwordMismatch'); throw new Error('profile.passwordChangeError'); } setMessage(t('profile.passwordChanged')); setPasswords({ currentPassword: '', newPassword: '', confirmPassword: '' }); } catch (cause) { setErrorKey(['profile.currentPasswordIncorrect', 'profile.passwordMin', 'profile.passwordMismatch', 'profile.passwordChangeError'].includes(cause.message) ? cause.message : 'profile.passwordChangeError'); } finally { setSaving(false); } }
  const displayedError = errorKey ? t(errorKey) : error;
  if (displayedError && !profile) return <main className="products-page"><p className="error" role="alert">{displayedError}</p></main>;
  if (!profile) return <main className="products-page"><p role="status">{t('profile.loading')}</p></main>;
  return <main className="products-page profile-page"><h1>{t('profile.title')}</h1>{message && <p className="success" role="status" aria-live="polite">{message}</p>}{displayedError && <p className="error" role="alert">{displayedError}</p>}<section className="product-form-card"><h2>{t('profile.details')}</h2><p><strong>{t('profile.email')}</strong> <bdi>{profile.email}</bdi></p><p><strong>{t('profile.created')}</strong> <bdi>{formatDisplayDate(profile.createdAt, i18n.language)}</bdi></p><form onSubmit={saveName} noValidate><label htmlFor="profile-name">{t('profile.fullName')}</label><input id="profile-name" value={name} onChange={(event) => setName(event.target.value)} /><button disabled={saving}>{saving ? t('profile.saving') : t('profile.saveName')}</button></form></section><section className="product-form-card"><h2>{t('profile.changePassword')}</h2><form onSubmit={changePassword} noValidate><label htmlFor="current-password">{t('profile.currentPassword')}</label><input id="current-password" type="password" value={passwords.currentPassword} onChange={(event) => setPasswords({ ...passwords, currentPassword: event.target.value })} /><label htmlFor="new-password">{t('profile.newPassword')}</label><input id="new-password" type="password" value={passwords.newPassword} onChange={(event) => setPasswords({ ...passwords, newPassword: event.target.value })} /><label htmlFor="confirm-password">{t('profile.confirmPassword')}</label><input id="confirm-password" type="password" value={passwords.confirmPassword} onChange={(event) => setPasswords({ ...passwords, confirmPassword: event.target.value })} /><button disabled={saving}>{saving ? t('profile.saving') : t('profile.changePassword')}</button></form></section></main>;
}
export default ProfilePage;
